### ISSUE TITLE
Detect enabled modules

### ISSUE THREAD

**Issue by simohell-fi** [druidfi/security-checker-action#11]
A drupal module may be installed via composer but that module or its submodule(s) may be not enabled.

Checking composer.lock against core.extensions.yml gives an overview on what are actual security risks.

F.e. Admin toolbar's submodule Admin toolbar search had a security recently update but while most sites use Admin toolbar only a few had the submodule enabled.

Also this would help removing unneccessary modules that are installed in the filesystem but not used.

**Comment by back-2-95** [comment]
Some notes as I have been implementing this:

- Modules like `stage_file_proxy` will be found as it's not enabled but there for development use (usually)
- If `admin_toolbar_search` is enabled in `core.extensions.yml` it will still not be found on composer.lock as it's submodule

So for the `stage_file_proxy` scenario: should we do a whitelist of such modules? E.g. `stage_file_proxy|devel` etc.

For `admin_toolbar_search` scenario: we'll find out if `admin_toolbar` has security updates and we won't skip showing the available update for a reason that submodule is not enabled (also there is no data which could be used for detecting this kind of scenario and we would be forced to code some module specific ifs). Thus making this scenario obsolete.

Now the output would be something like this:

```
## Security updates available

- `drupal/jsonapi_extras` is in composer.json but not enabled
- `drupal/stage_file_proxy` is in composer.json but not enabled
- `guzzlehttp/psr7` from 1.8.2 to [2.2.1](https://github.com/guzzlehttp/psr7/releases/tag/2.2.1)
```
